apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-guard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/just2courageous/green-guard.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}   # optional: auto-sync; remove if you want manual
