name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write        # commit the rollout stamp back to the repo
  packages: write        # push to GHCR
  id-token: write        # OIDC for AWS role

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: green-guard
      GHCR_REPO: ghcr.io/${{ github.repository_owner }}/green-guard

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---- GHCR login (GitHub Container Registry)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---- AWS creds via OIDC, then ECR login
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::399717050894:role/gh-actions-ecr
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---- Build ONCE and push to BOTH registries (GHCR + ECR)
      - name: Build & push (GHCR + ECR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.GHCR_REPO }}:latest
            ${{ env.GHCR_REPO }}:${{ github.sha }}
            ${{ steps.ecr.outputs.registry }}/${{ env.APP_NAME }}:latest
            ${{ steps.ecr.outputs.registry }}/${{ env.APP_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # ---- Make ArgoCD roll pods by changing the annotation
      - name: Stamp rollout with commit SHA
        run: |
          sha="${GITHUB_SHA}"
          sed -i 's#kubectl\.kubernetes\.io/restartedAt:.*#kubectl.kubernetes.io/restartedAt: "'$sha'"#' k8s/deployment.yaml

      - name: Commit manifest bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "ops: rollout ${GITHUB_SHA}" || echo "no changes"
          git push
