name: ci

on:
  push:
    branches: [ main ]

permissions:
  contents: write      # allow committing the rollout stamp back to the repo
  packages: write      # allow pushing image to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/green-guard:main

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # needed so we can commit & push later

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Make Argo Auto-Sync also roll the pods ---
      - name: Stamp rollout with commit SHA
        run: |
          sha="${GITHUB_SHA}"
          # Update the annotation value in k8s/deployment.yaml
          sed -i 's#kubectl\.kubernetes\.io/restartedAt:.*#kubectl.kubernetes.io/restartedAt: "'$sha'"#' k8s/deployment.yaml

      - name: Commit manifest bump
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "ops: rollout ${GITHUB_SHA}" || echo "no changes"
          git push
